### ISSUE TITLE
Installation details

### ISSUE THREAD

**Issue by fxxer** [kukulich/home-assistant-jablotron100#1]
What are the other parameters for setting up this integration?
Password and what is the slider?

**Comment by Shamshala** [comment]
Number of peripherals without base. If you ever tried F-Link, use the same number as the last sensor in your list.

**Comment by fxxer** [comment]
I got this `hiddev96,hidraw0: USB HID v1.11 Device [Jablotron ltd JA-100 Flexi] on usb-3f980000.usb-1.3/input0` from `dmesg | grep hid`

so I set up the integration:
- /dev/hidraw0
- second field is what? password, for what?
- then I put number of sensors

I get Error in the log:
`Logger: homeassistant.config_entries
Source: custom_components/jablotron100/jablotron.py:320
First occurred: 20:32:49 (2 occurrences)
Last logged: 20:40:26

Error setting up entry Jablotron for jablotron100
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 228, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/jablotron100/__init__.py", line 26, in async_setup_entry
    jablotron.initialize()
  File "/config/custom_components/jablotron100/jablotron.py", line 221, in initialize
    self._detect_central_unit()
  File "/config/custom_components/jablotron100/jablotron.py", line 320, in _detect_central_unit
    self._central_unit = reader.result(TIMEOUT)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 441, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError`

**Comment by Shamshala** [comment]
The password field is for your administrator code.

Not sure about the error.

**Comment by fxxer** [comment]
I used my administrator code, in the last try. The error is the same.

**Comment by Shamshala** [comment]
You can also try to report this to [discord](https://discord.gg/TcBtxE).

**Comment by Shamshala** [comment]
You can also try to report this to [discord](https://discord.gg/XYdCjpe).

**Comment by kukulich** [comment]
It fails because of timeout. It looks like an error in your connection between HA and Jablotron. You can increase the timeout here: https://github.com/kukulich/home-assistant-jablotron100/blob/master/custom_components/jablotron100/jablotron.py#L46

**Comment by kukulich** [comment]
@fxxer What's you jablotron version? There may be problem with the central unit detection.

**Comment by fxxer** [comment]
Where can I find the jablotron version?

**Comment by kukulich** [comment]
@fxxer In the F-link or J-link application.

**Comment by kukulich** [comment]
@fxxer There were many improvements lately so last version may work for you.

**Comment by fxxer** [comment]
With the new version it is working... :) I can arm all the sections, which is great. But I get data only from 1 of 4 motion detectors. Also how often are the sensor checked?

**Comment by kukulich** [comment]
@fxxer is this the only error in the log? How many sensors do you have?

**Comment by fxxer** [comment]
I have 4 sensors and only one is working.

3 sensors have the same error:

`2020-10-17 19:02:34 ERROR (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Unknown state packet of device 6: 55083e818001f009733b0010085800100000000024580010045800101000000045db04001b9d01002c9d0100000000212c040010183b08200b00000071300300
2020-10-17 19:02:39 ERROR (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Unknown state packet of device 5: 5508247d4001400ab33b0010522200100000000024580010045800101000000045db04001b9d01002c9d0100000000212c040010183b08200b00000071300300
2020-10-17 19:02:50 ERROR (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Unknown state packet of device 8: 55083e890002f10ad33b0010085800100000000024580010045800101000000045db04001b9d01002c9d0100000000212c040010183b08200b00000071300300
2020-10-17 19:02:54 ERROR (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Unknown state packet of device 8: 55083e890002310bf33b0010085800100000000054580010045800101000000045db04001b9d01002c9d0100000000212c040010183b08200b00000071300300`

**Comment by kukulich** [comment]
@fxxer It should be fixed in last version.

**Comment by fxxer** [comment]
Everything is working, thanks for quick fix. :)

**Comment by kukulich** [comment]
@fxxer Is you jablotron connected to LAN?

**Comment by fxxer** [comment]
@kukulich No
