### ISSUE TITLE
Error after update to 3.0.0 

### ISSUE THREAD

**Issue by matata86** [kukulich/home-assistant-jablotron100#11]
**Logger: homeassistant.config_entries
Source: custom_components/jablotron100/jablotron.py:1152
First occurred: 13:05:07 (1 occurrences)
Last logged: 13:05:07

Error setting up entry Jablotron for jablotron100
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/jablotron100/__init__.py", line 28, in async_setup_entry
    await jablotron.initialize()
  File "/config/custom_components/jablotron100/jablotron.py", line 315, in initialize
    self._detect_sections_and_pg_outputs()
  File "/config/custom_components/jablotron100/jablotron.py", line 554, in _detect_sections_and_pg_outputs
    self._parse_pg_outputs_states_packet(packet)
  File "/config/custom_components/jablotron100/jablotron.py", line 1152, in _parse_pg_outputs_states_packet
    for pg_output_number in range(1, self._config[CONF_NUMBER_OF_PG_OUTPUTS] + 1):
KeyError: 'number_of_pg_outputs'**

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in 3.0.1.
