### ISSUE TITLE
Failed to set up integration

### ISSUE THREAD

**Issue by hsk-dk** [kukulich/home-assistant-jablotron100#40]
I have used the integration with number of devices set to 0 for the last year. Today I deleted the integration, restarted, and reinstalled it. This time it setup the number of devices to the correct number (15) and completed the setup. This causes the setup to fail.
If i delete the integration again and set it up with 0 devices the setup is completet.
I have attached the debug logs:
2022-03-10 11:25:44 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration reolink_dev which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-10 11:25:44 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration microsoft_todo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-10 11:25:44 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-10 11:25:44 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-10 11:25:44 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration jablotron100 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-10 11:25:44 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration landroid_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-10 11:25:44 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-0_1) [custom_components.jablotron100] Outcoming: 300102
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-0_1) [custom_components.jablotron100] Outcoming: 300108
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-0_1) [custom_components.jablotron100] Outcoming: 300109
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-0_0) [custom_components.jablotron100] Incoming: 400c024a412d3130314b2d4c414e
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-0_0) [custom_components.jablotron100] Incoming: 400a084c4a36303432332e31
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-0_0) [custom_components.jablotron100] Incoming: 4008094c4a3136313230
2022-03-10 11:25:49 DEBUG (MainThread) [custom_components.jablotron100] Central unit: JA-101K-LAN (hardware: LJ60423.1, firmware: LJ16120)
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming: 80080339393932383335
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 1): 52020a01
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 2): 52020a02
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 3): 52020a03
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 5): 52020a05
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 6): 52020a06
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 7): 52020a07
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 8): 52020a08
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 15): 52020a0f
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming: 3a02010f
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 800d0c000000000000000002200a00
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:49 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 3b09010000000000000000
2022-03-10 11:25:50 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: d206db7f27000000
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 1): 52020a01
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 2): 52020a02
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 3): 52020a03
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 5): 52020a05
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 6): 52020a06
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 7): 52020a07
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 8): 52020a08
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming (device 15): 52020a0f
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_1) [custom_components.jablotron100] Outcoming: 3a02010f
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 520382fd0a
2022-03-10 11:25:51 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 3b09010000000000000000
2022-03-10 11:25:53 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Jablotron for jablotron100
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/jablotron100/__init__.py", line 22, in async_setup_entry
await jablotron_instance.initialize()
File "/config/custom_components/jablotron100/jablotron.py", line 271, in initialize
await self._detect_and_create_devices_and_sections_and_pg_outputs()
File "/config/custom_components/jablotron100/jablotron.py", line 282, in _detect_and_create_devices_and_sections_and_pg_outputs
self._detect_devices()
File "/config/custom_components/jablotron100/jablotron.py", line 654, in _detect_devices
packets = reader.result(estimated_duration * 2)
File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 447, in result
raise TimeoutError()
concurrent.futures._base.TimeoutError
2022-03-10 11:25:54 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.dlna_dmr
2022-03-10 11:25:54 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.dlna_dmr
2022-03-10 11:25:54 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.sonos
2022-03-10 11:25:59 DEBUG (ThreadPoolExecutor-1_0) [custom_components.jablotron100] Incoming: 512201000100070007000700070007000700070007000700070007000700070007000010

**Comment by kukulich** [comment]
There's startup check of devices when some devices are set.

It looks that the startup check does not get right responses about the devices. There's the same response for all devices `520382fd0a`. That's why it timeouts.

Does the user you use for HA have admin rights?

**Comment by hsk-dk** [comment]
I am running Home Assistant Operating System so my understanding is that HA is running with root privileges. is there a check i can complete to verify it?

**Comment by kukulich** [comment]
@hsk-dk We don't understand each other.

You added a PIN to the integration configuration. The PIN belongs to some Jablotron user - the Jablotron user needs admin rights (in Jablotron itself) to sniff devices.

**Comment by hsk-dk** [comment]
Sorry, i have a master user and a technical/service user. I know the error occurred if i use a normal user or the  technical/service user. but right now i can't remember if i have used the master user which has admin rights, i will double check and report back.
Thanks.

**Comment by hsk-dk** [comment]
I have just retried using the master user with admin rights, and the error is the same and the logs are the same.

**Comment by kukulich** [comment]
@hsk-dk unfortunatelly I don’t know the reason. You can try to sniff your communication via WireShark and Flink. We may find a reason what’s different in your Jablotron. I have the same central unit so it’s really strange.

**Comment by hsk-dk** [comment]
ok, i only have access the j-link, would the be enough? 
Else i will just continue to use the integration for basic arm disarmed states, which in itself is a huge benefit to my automations, so thanks for your work.

**Comment by kukulich** [comment]
@hsk-dk it may be enough but if you can join our Discord someone will send you Flink

**Comment by kukulich** [comment]
@hsk-dk Do you have any update?

**Comment by hsk-dk** [comment]
Sorry no, i have been unable to figure out how to use wireshark. So i am closing this issue
