### ISSUE TITLE
Electricity pulse meter doesn’t work

### ISSUE THREAD

**Issue by Tomm206** [kukulich/home-assistant-jablotron100#67]
Hi,

I can’t see any data from electricity pulse meter after upgrade to HA version 2023.2.x (there should be increasing trend on the graph). The Jablotron app normally shows data but no new data in HA after this upgrade:

![image](https://user-images.githubusercontent.com/95053956/221228068-b1a4a2ad-2dc2-42b7-99f3-ba1d419c716e.png)

Thanks

**Comment by kukulich** [comment]
What integration version do you use?

**Comment by Tomm206** [comment]
It is 3.16.0

**Comment by kukulich** [comment]
Please try to enable debug for devices, see README. Please try to log some packets for the electricity pulse device.

**Comment by Tomm206** [comment]
I enabled debug logging in Jablotron integration. 

![image](https://user-images.githubusercontent.com/95053956/221350898-53cb7479-0be0-4187-ae59-b965148f491f.png)

But I cannot download diagnostics. I could see a problem with server:

![image](https://user-images.githubusercontent.com/95053956/221350962-397afd70-e1e1-4741-b844-32e98abeb71c.png)

When I checked the HA core log I could see there this (but propably doesn’t relate with the problem above):

Logger: aiohttp.server
Source: custom_components/jablotron100/jablotron.py:1144
Integration: jablotron100 ([documentation](https://github.com/kukulich/home-assistant-jablotron100), [issues](https://github.com/kukulich/home-assistant-jablotron100/issues))
First occurred: 10:51:49 AM (3 occurrences)
Last logged: 10:56:13 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 246, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
  File "/config/custom_components/jablotron100/diagnostics.py", line 26, in async_get_config_entry_diagnostics
    "section": jablotron_instance.get_device_section(device_number),
  File "/config/custom_components/jablotron100/jablotron.py", line 1144, in get_device_section
    return self._devices_data[device_id][DeviceData.SECTION]
KeyError: 'device_10'

**Comment by kukulich** [comment]
It looks your configuration is broken - you should install the Jablotron integration from the scratch.

**Comment by Tomm206** [comment]
I have there many other devices and sensors from Jablotron integration and they work normally except pulse meter.

**Comment by Chilliriha** [comment]
Does anyone the same isue? The only working version on my Home Assistant Core 2024.1.6 is 3.23.1  - is showing the Pulse entity. The newest version - Pulse still unaviable. I also tried completely new instalation of HA with the same result.

**Comment by Tomm206** [comment]
I still have the same problem. The pulse meter doesn't work anymore. I haven't tested which version works and which doesn't. I only tried changing the type of sensor, but it didn't help. I haven't found any advice, so I gave up on that.

**Comment by kukulich** [comment]
I’m lazy to check the code but I think the pulse entity is added dynamically. You can wait if the entity is not added later when jablotron reports pulse
