### ISSUE TITLE
USB Device not recognized (JA-100K)

### ISSUE THREAD

**Issue by Mighty5nake** [kukulich/home-assistant-jablotron100#97]
Hi,

i'm running the latest version of HA : 

hassos : 12.4
homeassistant : 2024.8.1

I receive this error in the Logs : 

Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 12:31:52 AM (1 occurrences)
Last logged: 12:31:52 AM

Detected blocking call to listdir with args ('/sys/class/hidraw',) inside the event loop by custom integration 'jablotron100' at custom_components/jablotron100/jablotron.py, line 2724: return Jablotron._check_possible_paths_for_serial_port(os.listdir(HIDRAW_PATH)) (offender: /config/custom_components/jablotron100/jablotron.py, line 2724: return Jablotron._check_possible_paths_for_serial_port(os.listdir(HIDRAW_PATH))), please create a bug report at https://github.com/kukulich/home-assistant-jablotron100/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 459, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle resp = await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/jablotron100/config_flow.py", line 180, in async_step_user serial_port = Jablotron.detect_serial_port() File "/config/custom_components/jablotron100/jablotron.py", line 2724, in detect_serial_port return Jablotron._check_possible_paths_for_serial_port(os.listdir(HIDRAW_PATH))

when i search for the USB device i receive this error : 

![image](https://github.com/user-attachments/assets/97ca816a-1367-4ff9-8bdc-5da608b4ff17)

i am new in the reporting of errors so if you want me to provide more information please tell me how.

regards

**Comment by Mighty5nake** [comment]
Problem solved itself with Discord communication, my 10m USB cable did not have enough power on the 3 USB ports on the back. There is one separate USB port on the side and now the device is working like it should be.
